name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: Publish to Docker Hub
      run: |
        docker login --username ${DOCKERHUB_USERNAME} --password ${DOCKERHUB_PASSWORD}
        docker-compose push
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}

